### ISSUE TITLE
Clean out the Developer Version when deploying to Production

### ISSUE THREAD

**Issue by chriswmackey** [pollination/pollination-dsl#87]
It seems that we get the developer version whenever we deploy a private recipe like this to production:

![image](https://user-images.githubusercontent.com/5567574/110162072-3b785e80-7dbc-11eb-8237-a69c87f815ef.png)

@mostaphaRoudsari 's current hypothesis is that the version is not being passed through this part of the code:
https://github.com/pollination/pollination-dsl/blob/fc77ca5f3e2c3673c32e237e081ff10ecdfdedbf/pollination_dsl/common.py#L229-L248

I will leave it for him to debug when he gets the chance.

**Comment by mostaphaRoudsari** [comment]
NOTE: This is only an issue for private recipes when we have to use pip install .
